{
 "title": "OpenZR+ Cisco 8201 port 0/0/0/8 - Circuit ID 1001",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PortNumber", "query": "0/0/0/8" },
   { "name": "SrcIpAddress", "query": "172.30.150.130" },
   { "name": "OpticsPortNumber", "query": "Optics0/0/0/8" },
   { "name": "CoherentDSPPortNumber", "query": "CoherentDSP0/0/0/8" },
   { "name": "EthernetPortName", "query": "FourHundredGigE0/0/0/8" }
  ]
 },
 "panels": [
  {
   "title": "Transceiver Modulation",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Modulation",
     "measurement": "cisco_port_dwdm_port",
     "query": "SELECT last(\"derived_optics_type\") FROM \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$SrcIpAddress$/ AND \"name\" =~ /^$OpticsPortNumber$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "modulation_type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "Bandwidth",
     "measurement": "cisco_port_dwdm_controller",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "Incoming Traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_ethernet_statistics_float",
     "query": "SELECT derivative(mean(\"bytes_received\"), 1s)  * 8 FROM \"autogen\".\"cisco_port_ethernet_statistics_float\" WHERE (\"interface_name\"::tag =~ /^$EthernetPortName$/ AND \"source\"::tag =~ /^$SrcIpAddress$/) AND $timeFilter GROUP BY time($__interval), \"source\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " * 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "interface_name::tag", "operator": "=~", "value": "/^$EthernetPortName$/" },
      { "condition": "AND", "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" }
     ]
    },
    {
     "alias": "Outgoing Traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_ethernet_statistics_float",
     "query": "SELECT derivative(mean(\"bytes_received\"), 1s)  * 8 FROM \"autogen\".\"cisco_port_ethernet_statistics_float\" WHERE (\"interface_name\"::tag =~ /^$EthernetPortName$/ AND \"source\"::tag =~ /^$SrcIpAddress$/) AND $timeFilter GROUP BY time($__interval), \"source\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ " * 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface_name::tag", "operator": "=~", "value": "/^$EthernetPortName$/" },
      { "condition": "AND", "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" }
     ]
    }
   ]
  },
  {
   "title": "Transceiver Type",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "Type",
     "measurement": "cisco_port_dwdm_port",
     "query": "SELECT last(\"derived_optics_type\") FROM \"gNMI-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$SrcIpAddress$/ AND \"name\" =~ /^$OpticsPortNumber$/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "derived_optics_type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "FEC Type",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "targets": [
    {
     "alias": "FEC",
     "measurement": "cisco_port_dwdm_controller",
     "select": [
      [
       { "params": [ "fec_mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Power Levels  in dBm ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "lane_data_0_receive_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Tx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "lane_data_0_transmit_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Configured Values",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "THz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Frequency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "query": "SELECT mean(\"dwdm_carrier_frequency\") FROM \"gNMI-Float-Cisco-IOS-XR-controller-optics-oper:/optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" =~ /^$SrcIpAddress$/ AND \"name\" =~ /^$OpticsPortNumber$/) AND $timeFilter GROUP BY time($__interval), \"name\", \"source\" fill(null)",
     "select": [
      [
       { "params": [ "dwdm_carrier_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Tx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "cfg_tx_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "OpenZR+ Optical Power Levels in dBm",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 6 },
   "targets": [
    {
     "alias": "$tag_source $tag_name Rx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "lane_data_0_receive_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "$tag_source $tag_name Tx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "lane_data_0_transmit_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Bit Error Rates",
   "type": "timeseries",
   "description": "BER values below 0.01 are healthy, between 0.01-0.02 indicates need for maintenance, and above 0.02 indicates likeliness of transport packet loss.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 6 },
   "targets": [
    {
     "alias": "Post FEC BER",
     "measurement": "cisco_port_dwdm_controller_float",
     "select": [
      [
       { "params": [ "otu_fec_satistics_post_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    },
    {
     "alias": "Pre FEC BER",
     "measurement": "cisco_port_dwdm_controller_float",
     "select": [
      [
       { "params": [ "otu_fec_satistics_pre_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Bit Error Rates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Post FEC BER",
     "measurement": "cisco_port_dwdm_controller_float",
     "query": "SELECT \"otu_fec_satistics_post_fec_ber\" FROM \"gNMI-Float-Cisco-IOS-XR-controller-otu-oper:/otu/controllers/controller/info\" WHERE (\"source\"::tag = '172.30.150.130' AND \"controller_name\"::tag =~ /^$CoherentDSPPortNumber$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "otu_fec_satistics_post_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name::tag", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    },
    {
     "alias": "Pre FEC BER",
     "measurement": "cisco_port_dwdm_controller_float",
     "select": [
      [
       { "params": [ "otu_fec_satistics_pre_fec_ber" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name::tag", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Environmentals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Environmentals",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 11 },
   "targets": [
    {
     "alias": "°C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Volt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Q margin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Q Factor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_controller_float",
     "query": "SELECT mean(\"snr\") FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" = '8201') AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "qfactor" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    },
    {
     "alias": "Q margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_controller_float",
     "select": [
      [
       { "params": [ "qmargin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Signal to Noise Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OSNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "optical_signal_to_noise_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "OSNR Margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "optical_signal_to_noise_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " - 24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Impairments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 14 },
   "targets": [
    {
     "alias": "Chromatic Dispersion ps/nm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "cd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "2nd Order PMD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "query": "SELECT mean(\"snr\") FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" = '8201') AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "second_order_polarization_mode_dispersion"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Differential Group Delay ps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "differential_group_delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal to Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 16 },
   "targets": [
    {
     "alias": "OSNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "optical_signal_to_noise_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Q Factor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "query": "SELECT mean(\"snr\") FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" = '8201') AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       { "params": [ "qfactor" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" }
     ]
    },
    {
     "alias": "Q Margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "qmargin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "controller_name", "operator": "=~", "value": "/^$CoherentDSPPortNumber$/" },
      { "condition": "AND", "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Impairments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ps/nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Chromatic Dispersion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "cd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "2nd Order PMD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "query": "SELECT mean(\"snr\") FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" = '8201') AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "second_order_polarization_mode_dispersion"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    },
    {
     "alias": "Differential Group Delay",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cisco_port_dwdm_port_float",
     "select": [
      [
       { "params": [ "differential_group_delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$SrcIpAddress$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$OpticsPortNumber$/" }
     ]
    }
   ]
  }
 ]
}