{
 "title": "OpenZR+ Nokia port 1/1/c28 - Circuit ID 2000",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "PortNumber", "query": "1/1/c28" },
   { "name": "EthPortNumber", "query": "1/1/c28/1" },
   { "name": "HostName", "query": "172.30.150.150" }
  ]
 },
 "panels": [
  {
   "title": "Transceiver Type",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Type",
     "measurement": "nokia_port_string",
     "query": "SELECT last(\"transceiver_type\") FROM \"nokia_port_string\" WHERE (\"source\"::tag =~ /^$HostName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "transceiver_type" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "Transceiver Part Number",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "Part Number",
     "measurement": "nokia_port_string",
     "select": [
      [
       { "params": [ "transceiver_vendor_part_number" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "Incoming Traffic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_ethernet_statistics",
     "query": "SELECT 8 * derivative(mean(\"in_octets\"),1s) FROM \"nokia_port_ethernet_statistics\" WHERE (\"source\" =~ /^$HostName$/ AND \"port_id\" = '$EthPortNumber') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "in_octets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "172.30.150.150" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "1/1/c34/1" }
     ]
    },
    {
     "alias": "Outgoing Traffic",
     "query": "SELECT 8 * derivative(mean(\"out_octets\"),1s) FROM \"nokia_port_ethernet_statistics\" WHERE (\"source\" =~ /^$HostName$/ AND \"port_id\" = '$EthPortNumber') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Transceiver Bandwidth",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "targets": [
    {
     "alias": "Bandwidth",
     "measurement": "nokia_port_ethernet",
     "select": [
      [
       { "params": [ "oper_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "Transceiver Serial Number",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "alias": "Serial Number",
     "measurement": "nokia_port_string",
     "select": [
      [
       {
        "params": [
         "transceiver_vendor_serial_number"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Power Levels  in dBm ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Rx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "query": "SELECT last(\"coherent_statistics_received_power_current\")  / 100 FROM \"nokia_port_dwdm\" WHERE (\"port_id\"::tag =~ /^$PortNumber$/) AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_power_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "port_id::tag", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Tx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_transmitted_power_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Configured Values",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "THz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tx Target Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_configure",
     "select": [
      [
       { "params": [ "dwdm_coherent_target_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id::tag", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "ITU Channel",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_configure",
     "select": [
      [
       { "params": [ "dwdm_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "OpenZR+ Optical Power Levels in dBm",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 6 },
   "targets": [
    {
     "alias": "Rx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_power_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Tx Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_transmitted_power_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Bit Error Rate",
   "type": "timeseries",
   "description": "BER values below 0.01 are healthy, between 0.01-0.02 indicates need for maintenance, and above 0.02 indicates likeliness of transport packet loss.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 6 },
   "targets": [
    {
     "alias": "Pre FEC BER",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_bit_error_rate_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Coherent Frame Error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_media_frame_error_count_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id::tag", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Bit Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "BER" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Pre FEC BER",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_bit_error_rate_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Environmentals",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature °C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_transceiver",
     "select": [
      [
       {
        "params": [
         "digital_diagnostic_monitoring_temperature_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_transceiver",
     "select": [
      [
       {
        "params": [
         "digital_diagnostic_monitoring_supply_voltage_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Environmentals",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 11 },
   "targets": [
    {
     "alias": "°C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_transceiver",
     "select": [
      [
       {
        "params": [
         "digital_diagnostic_monitoring_temperature_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_transceiver",
     "select": [
      [
       {
        "params": [
         "digital_diagnostic_monitoring_supply_voltage_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Q margin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Q Factor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "query": "SELECT mean(\"snr\") FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" = '8201') AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_quality_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id::tag", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Q margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       { "params": [ "coherent_rx_quality_margin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id::tag", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Signal to Noise Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OSNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_optical_signal_to_noise_ratio_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "OSNR Margin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_optical_signal_to_noise_ratio_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/10 - 24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Impairments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 14 },
   "targets": [
    {
     "alias": "Chromatic Dispertion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_chromatic_dispersion_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "$PortNumber" }
     ]
    },
    {
     "alias": "Differential Group Delay",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_differential_group_delay_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "$PortNumber" }
     ]
    }
   ]
  },
  {
   "title": "Optics Signal to Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 16 },
   "targets": [
    {
     "alias": "OSNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_optical_signal_to_noise_ratio_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "ESNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_electrical_signal_to_noise_ratio_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  },
  {
   "title": "Optical Impairments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ps/nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Chromatic Dispersion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_chromatic_dispersion_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "Differential Group Delay",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "query": "SELECT mean(\"snr\") FROM \"Cisco-IOS-XR-controller-optics-oper:optics-oper/optics-ports/optics-port/optics-info\" WHERE (\"source\" = '8201') AND $timeFilter GROUP BY time($__interval), \"source\", \"name\" fill(null)",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_differential_group_delay_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    },
    {
     "alias": "ESNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "controller_name" ], "type": "tag" },
      { "params": [ "source" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nokia_port_dwdm",
     "select": [
      [
       {
        "params": [
         "coherent_statistics_received_electrical_signal_to_noise_ratio_current"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "port_id", "operator": "=", "value": "/^$PortNumber$/" }
     ]
    }
   ]
  }
 ]
}